# Generated by Django 3.0.5 on 2020-07-30 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelTable(
            name='grades',
            table='grades',
        ),
        migrations.AlterModelTable(
            name='student',
            table='students',
        ),
    ]
